### PR TITLE
BreakBeforeBinaryOperators: None

### PR DESCRIPTION
**Pull request by drwells**
I very much prefer this setting!

### CODE REVIEW

**Comment by drwells** [comment]
I skipped updating the tests.

**Comment by drwells** [comment]
This is one of the few places where I really have a strong preference for one style over another. I have a lot of trouble seeing binary operators when they are at the beginning of a line with stuff overhead and will lobby very strongly to do it this way.

**Comment by davydden** [comment]
@drwells i also like it better this way.

**Comment by masterleinad** [comment]
I tried to follow what we do in the majority of places (`*` and `+` at the beginning vs. end of lines in files in the `source` directory) here. I slightly prefer the current setting.

**Pull request closed without merging**
