### PR TITLE
Fixed issues from pull request to dealii master.

### PR DESCRIPTION
**Pull request by samiiali**
Fixed issues from pull request to dealii master.

### CODE REVIEW

**Comment by masterleinad** [comment]
Would you mind to also update the output files for the test before merging? Martin is certainly right, that in case more than process is used only the first one creates output. Simply use `MPILogInitAll log;` instead of 
`std::ofstream logfile("output");
deallog.attach(logfile, false);
deallog.threshold_double(1.e-10);`

**Comment by samiiali** [comment]
I will fix it right now.

**Comment by samiiali** [comment]
Done.

**Comment by masterleinad** [comment]
Great! Would you update the output files as well? This way the tests are going to fail.
I think it is fine to rebase all this into one commit.

**Comment by samiiali** [comment]
I hope, this was what you asked for. Otherwise, let me know. I am completely open to your suggestions Daniel !!

**Comment by samiiali** [comment]
I am changing a small issue. Just a second ... do not merge .

**Comment by samiiali** [comment]
Hopefully, ready to be merged.

**Comment by masterleinad** [comment]
Yes, exactly. Probably we need to discuss if and how to combine the old neighbor functions with the new periodic neighbor functions as Martin already pointed out.

**Pull request merged**
